/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: 10
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types
type StepModule = Record<string, (input: any) => Promise<any>>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
  "Generate Text": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-text/step"),
    stepFunction: "generateTextStep",
  },
  "Generate Image": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-image/step"),
    stepFunction: "generateImageStep",
  },
  Scrape: {
    importer: () => import("@/plugins/firecrawl/steps/scrape/step"),
    stepFunction: "firecrawlScrapeStep",
  },
  Search: {
    importer: () => import("@/plugins/firecrawl/steps/search/step"),
    stepFunction: "firecrawlSearchStep",
  },
  "Create Ticket": {
    importer: () => import("@/plugins/linear/steps/create-ticket/step"),
    stepFunction: "createTicketStep",
  },
  "Find Issues": {
    importer: () => import("@/plugins/linear/steps/find-issues/step"),
    stepFunction: "findIssuesStep",
  },
  "Send Email": {
    importer: () => import("@/plugins/resend/steps/send-email/step"),
    stepFunction: "sendEmailStep",
  },
  "Send Slack Message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message/step"),
    stepFunction: "sendSlackMessageStep",
  },
  "Create Chat": {
    importer: () => import("@/plugins/v0/steps/create-chat/step"),
    stepFunction: "createChatStep",
  },
  "Send Message": {
    importer: () => import("@/plugins/v0/steps/send-message/step"),
    stepFunction: "sendMessageStep",
  },
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}
