#!/usr/bin/env tsx
/**
 * Plugin Auto-Discovery Script
 *
 * Automatically discovers all plugins in the plugins/ directory and generates
 * the plugins/index.ts file with imports. Also updates the README.md with
 * the current list of available actions.
 *
 * Run this script:
 * - Manually: pnpm discover-plugins
 * - Automatically: Before build (in package.json)
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const PLUGINS_DIR = join(process.cwd(), "plugins");
const OUTPUT_FILE = join(PLUGINS_DIR, "index.ts");
const TYPES_FILE = join(process.cwd(), "lib", "types", "integration.ts");
const STEP_REGISTRY_FILE = join(process.cwd(), "lib", "step-registry.ts");
const README_FILE = join(process.cwd(), "README.md");
const PLUGINS_MARKER_REGEX =
  /<!-- PLUGINS:START[^>]*-->[\s\S]*?<!-- PLUGINS:END -->/;

// Regex to validate JavaScript identifiers
const VALID_IDENTIFIER_REGEX = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

// System integrations that don't have plugins
const SYSTEM_INTEGRATION_TYPES = ["database"] as const;

/**
 * Discover all plugin directories
 */
function discoverPlugins(): string[] {
  const entries = readdirSync(PLUGINS_DIR);

  const plugins = entries.filter((entry) => {
    // Skip special directories and files
    if (
      entry.startsWith("_") ||
      entry.startsWith(".") ||
      entry === "index.ts" ||
      entry === "registry.ts"
    ) {
      return false;
    }

    // Only include directories
    const fullPath = join(PLUGINS_DIR, entry);
    try {
      return statSync(fullPath).isDirectory();
    } catch {
      return false;
    }
  });

  return plugins.sort();
}

/**
 * Generate the plugins/index.ts file
 */
function generateIndexFile(plugins: string[]): void {
  const imports = plugins.map((plugin) => `import "./${plugin}";`).join("\n");

  const content = `/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * Discovered plugins: ${plugins.join(", ") || "none"}
 */

${imports || "// No plugins discovered"}

export type { IntegrationPlugin } from "./registry";

// Export the registry utilities
export {
  findActionById,
  getActionsByCategory,
  getAllActions,
  getAllIntegrations,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getSortedIntegrationTypes,
  registerIntegration,
} from "./registry";
`;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
}

/**
 * Update the README.md with the current list of actions
 */
async function updateReadme(): Promise<void> {
  // Dynamically import the plugins to populate the registry
  // This works because we already generated plugins/index.ts above
  await import("@/plugins/index");

  // Now import the registry utilities
  const { getAllIntegrations } = await import("@/plugins/registry");

  const integrations = getAllIntegrations();

  if (integrations.length === 0) {
    console.log("⚠️  No integrations found, skipping README update");
    return;
  }

  // Generate markdown list grouped by integration
  const actionsList = integrations
    .map((integration) => {
      const actionLabels = integration.actions.map((a) => a.label).join(", ");
      return `- **${integration.label}**: ${actionLabels}`;
    })
    .join("\n");

  // Read current README
  const readme = readFileSync(README_FILE, "utf-8");

  // Check if markers exist
  if (!readme.includes("<!-- PLUGINS:START")) {
    console.log("⚠️  README markers not found, skipping README update");
    return;
  }

  // Replace content between markers
  const updated = readme.replace(
    PLUGINS_MARKER_REGEX,
    `<!-- PLUGINS:START - Do not remove. Auto-generated by discover-plugins -->\n${actionsList}\n<!-- PLUGINS:END -->`
  );

  writeFileSync(README_FILE, updated, "utf-8");
  console.log(
    `📝 Updated README.md with ${integrations.length} integration(s)`
  );
}

/**
 * Generate the lib/types/integration.ts file with dynamic types
 */
async function generateTypesFile(): Promise<void> {
  // Ensure the types directory exists
  const typesDir = dirname(TYPES_FILE);
  if (!existsSync(typesDir)) {
    mkdirSync(typesDir, { recursive: true });
  }

  // Get plugin types from registry
  const { getIntegrationTypes } = await import("@/plugins/registry");
  const pluginTypes = getIntegrationTypes();

  // Combine plugin types with system types
  const allTypes = [...pluginTypes, ...SYSTEM_INTEGRATION_TYPES].sort();

  // Generate the union type
  const unionType = allTypes.map((t) => `  | "${t}"`).join("\n");

  const content = `/**
 * Integration Types (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration type:
 * 1. Create a plugin in plugins/ directory, OR
 * 2. Add a system integration to SYSTEM_INTEGRATION_TYPES in discover-plugins.ts
 * 3. Run: pnpm discover-plugins
 *
 * Generated types: ${allTypes.join(", ")}
 */

// Integration type union - plugins + system integrations
export type IntegrationType =
${unionType};

// Generic config type - plugins define their own keys via formFields[].configKey
export type IntegrationConfig = Record<string, string | undefined>;
`;

  writeFileSync(TYPES_FILE, content, "utf-8");
  console.log(
    `📝 Generated lib/types/integration.ts with ${allTypes.length} type(s)`
  );
}

/**
 * Generate the lib/step-registry.ts file with step import functions
 * This enables dynamic imports that are statically analyzable by the bundler
 */
async function generateStepRegistry(): Promise<void> {
  const { getAllIntegrations } = await import("@/plugins/registry");
  const integrations = getAllIntegrations();

  // Collect all action -> step mappings
  const stepEntries: Array<{
    actionId: string;
    integration: string;
    stepImportPath: string;
    stepFunction: string;
  }> = [];

  for (const integration of integrations) {
    for (const action of integration.actions) {
      stepEntries.push({
        actionId: action.id,
        integration: integration.type,
        stepImportPath: action.stepImportPath,
        stepFunction: action.stepFunction,
      });
    }
  }

  // Generate the step importer map with static imports
  // Use unquoted keys when valid identifiers, quoted otherwise
  const isValidIdentifier = (str: string) => VALID_IDENTIFIER_REGEX.test(str);

  const importerEntries = stepEntries
    .map(({ actionId, integration, stepImportPath, stepFunction }) => {
      const key = isValidIdentifier(actionId) ? actionId : `"${actionId}"`;
      return `  ${key}: {
    importer: () => import("@/plugins/${integration}/steps/${stepImportPath}/step"),
    stepFunction: "${stepFunction}",
  },`;
    })
    .join("\n");

  const content = `/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: ${stepEntries.length}
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types
type StepModule = Record<string, (input: any) => Promise<any>>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
${importerEntries}
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}
`;

  writeFileSync(STEP_REGISTRY_FILE, content, "utf-8");
  console.log(
    `📝 Generated lib/step-registry.ts with ${stepEntries.length} step(s)`
  );
}

/**
 * Main execution
 */
async function main(): Promise<void> {
  console.log("🔍 Discovering plugins...");

  const plugins = discoverPlugins();

  if (plugins.length === 0) {
    console.log("⚠️  No plugins found in plugins/ directory");
  } else {
    console.log(`✅ Found ${plugins.length} plugin(s):`);
    for (const plugin of plugins) {
      console.log(`   - ${plugin}`);
    }
  }

  console.log("\n📝 Generating plugins/index.ts...");
  generateIndexFile(plugins);

  console.log("📚 Updating README.md...");
  await updateReadme();

  console.log("🔧 Generating lib/types/integration.ts...");
  await generateTypesFile();

  console.log("🔧 Generating lib/step-registry.ts...");
  await generateStepRegistry();

  console.log("✨ Done! Plugin registry updated.\n");
}

main().catch((error) => {
  console.error("❌ Error:", error);
  process.exit(1);
});
